/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.validation;

import dk.itu.dsl.roboprose.validation.AbstractRoboProseValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RoboProseValidator extends AbstractRoboProseValidator {
}
