// (c) mdsebook, wasowski, berger
//
// Runs the code generators from command line.  The easiest way to execute it:
//
// sbt run -> and then select mdsebook.fsm.xtext.scala.Generators
//
// In Eclipse you should be able to just right click this file and Run as > Scala Application.
//
// (otherwise you can package as a standalone JVM application)
// Right now the input file name is hard coded below, but you can easily
// change this to use command line arguments

package dk.itu.dsl.roboprose.richban.xtext

import scala.collection.JavaConversions._

import dk.itu.dsl.roboprose.model._
import mdsebook.scala.EMFScala._
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl
import org.eclipse.emf.ecore.util._
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.resource.XtextResourceSet
import org.eclipse.emf.ecore.resource._
import java.io.PrintWriter
import java.nio._
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl
import dk.itu.dsl.roboprose.constraints.Main

object Compiler extends App {

  var instanceFileName = ""

  if (args.length == 0) {
    println("Please specify a file:")
    instanceFileName = scala.io.StdIn.readLine()
  } else {
    instanceFileName = args(0)
  }


  //Strip the extension and add .xmi
  val preExtension = instanceFileName.lastIndexOf(".")
  val outputFileName = instanceFileName.substring(0,preExtension)+".xmi"


  // Register our meta-model package for abstract syntax
  RoboprosePackage.eINSTANCE.eClass

  // register a resource factory for XMI files
  Resource.Factory.Registry.INSTANCE.
  getExtensionToFactoryMap.put("xmi", new XMIResourceFactoryImpl)


  // Register a suitable resource factory for FSM files (generated by Xtext)
  // The "Fsm" prefix is the name of our language
  // it needs to change to refer to code generated for your language
  new RoboProseStandaloneSetup().createInjectorAndDoEMFRegistration

  // we are loading our file here
  val uri = URI.createURI(instanceFileName)
  var resource = new ResourceSetImpl().getResource(uri, true);

  EcoreUtil.resolveAll(resource)

  // Get Java Object Robot Instance
  val robot = EcoreUtil.getAllProperContents[EObject](resource, false)
  val constraintsPassed = Main.checkInstances(Stream((instanceFileName, robot)))

  // Checking Constraints
  if (constraintsPassed) {

    val xmiResource = new ResourceSetImpl().createResource(URI.createURI(outputFileName))

    xmiResource.getContents().add(resource.getContents().get(0))

    xmiResource.save(null)
  }

  // The call to get(0) below gives you the first model root.
  // If you open a directory instead of a file,
  // you can iterate over all models in it,
  // by changing 0 to a suitable index
  //val m: Root = resource.getContents.asInstanceOf[Root]

  //println(m)


}
