/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.serializer;

import com.google.inject.Inject;
import dk.itu.dsl.roboprose.services.RoboProseGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class RoboProseSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RoboProseGrammarAccess grammarAccess;
	protected AbstractElementAlias match_EventListener_WhenKeyword_0_0_or_WhenKeyword_0_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RoboProseGrammarAccess) access;
		match_EventListener_WhenKeyword_0_0_or_WhenKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getEventListenerAccess().getWhenKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getEventListenerAccess().getWhenKeyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getActionDelimiterRule())
			return getActionDelimiterToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getParagraphDelimiterRule())
			return getParagraphDelimiterToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSublistenerDelimiterRule())
			return getSublistenerDelimiterToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * ActionDelimiter:
	 * 	(("and" "then") | ("," "then") | ("." "Then")) ("it" "should")?
	 * ;
	 */
	protected String getActionDelimiterToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "andthen";
	}
	
	/**
	 * ParagraphDelimiter:
	 * 	'.' NEWLINE NEWLINE+
	 * ;
	 */
	protected String getParagraphDelimiterToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ".\n";
	}
	
	/**
	 * SublistenerDelimiter:
	 * 	'.'
	 * ;
	 */
	protected String getSublistenerDelimiterToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ".";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_EventListener_WhenKeyword_0_0_or_WhenKeyword_0_1.equals(syntax))
				emit_EventListener_WhenKeyword_0_0_or_WhenKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'When' | 'when'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'it' event=Event
	 */
	protected void emit_EventListener_WhenKeyword_0_0_or_WhenKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
