/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.formatting2;

import com.google.inject.Inject;
import dk.itu.dsl.roboprose.services.RoboProseGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class RoboProseFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private RoboProseGrammarAccess _roboProseGrammarAccess;
  
  protected void _format(final /* RoboProse */Object roboProse, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ngetMain cannot be resolved"
      + "\nformat cannot be resolved"
      + "\ngetListeners cannot be resolved");
  }
  
  protected void _format(final /* Main */Object main, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nAction cannot be resolved to a type."
      + "\ngetActions cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  public void format(final Object roboProse, final IFormattableDocument document) {
    if (roboProse instanceof XtextResource) {
      _format((XtextResource)roboProse, document);
      return;
    } else if (roboProse instanceof EObject) {
      _format((EObject)roboProse, document);
      return;
    } else if (roboProse == null) {
      _format((Void)null, document);
      return;
    } else if (roboProse != null) {
      _format(roboProse, document);
      return;
    } else if (roboProse != null) {
      _format(roboProse, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(roboProse, document).toString());
    }
  }
}
