/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.ide;

import dk.itu.dsl.roboprose.ide.AbstractRoboProseIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RoboProseIdeModule extends AbstractRoboProseIdeModule {
}
