/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.itu.dsl.roboprose.RoboProseRuntimeModule;
import dk.itu.dsl.roboprose.RoboProseStandaloneSetup;
import dk.itu.dsl.roboprose.ide.RoboProseIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RoboProseIdeSetup extends RoboProseStandaloneSetup {
  @Override
  public Injector createInjector() {
    RoboProseRuntimeModule _roboProseRuntimeModule = new RoboProseRuntimeModule();
    RoboProseIdeModule _roboProseIdeModule = new RoboProseIdeModule();
    return Guice.createInjector(Modules2.mixin(_roboProseRuntimeModule, _roboProseIdeModule));
  }
}
