/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRoboProseScopeProvider extends DelegatingScopeProvider {
}
