/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.frontend.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RoboProseStandaloneSetup extends RoboProseStandaloneSetupGenerated {

	def static void doSetup() {
		new RoboProseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
