/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose;

import dk.itu.dsl.roboprose.AbstractRoboProseRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RoboProseRuntimeModule extends AbstractRoboProseRuntimeModule {
}
