/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose;

import dk.itu.dsl.roboprose.RoboProseStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RoboProseStandaloneSetup extends RoboProseStandaloneSetupGenerated {
  public static void doSetup() {
    new RoboProseStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
