/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.tests;

import com.google.inject.Inject;
import dk.itu.dsl.roboprose.tests.RoboProseInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(RoboProseInjectorProvider.class)
@SuppressWarnings("all")
public class RoboProseParsingTest {
  @Inject
  private /* ParseHelper<Action> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field RoboProseParsingTest.parseHelper refers to the missing type Action"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
