<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.itu.dk/dsl/roboprose" nsPrefix="roboprose">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robots" lowerBound="1"
        upperBound="-1" eType="#//RoboProse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoboProse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="#//Main" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listeners" upperBound="-1"
        eType="#//EventListener" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RotorAction" abstract="true" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Move" eSuperTypes="#//RotorAction #//hasDuration #//randomizable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//MOVE_DIRECTION" defaultValueLiteral="forwards"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Turn" eSuperTypes="#//RotorAction #//hasDuration #//randomizable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degrees" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="90.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//TURN_DIRECTION" defaultValueLiteral="left"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stop" eSuperTypes="#//Action #//hasDuration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shouldRepeat" lowerBound="1"
        eType="#//SHOULD_REPEAT" defaultValueLiteral="dontRepeat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventListener">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//Event"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sublisteners" upperBound="-1"
        eType="#//EventListener" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Obstacle" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tapped" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="hasDuration" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="randomizable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRandom" eType="#//RANDOM"
        defaultValueLiteral="notRandom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MOVE_DIRECTION">
    <eLiterals name="FORWARDS" value="1" literal="forwards"/>
    <eLiterals name="BACKWARDS" literal="backwards"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TURN_DIRECTION">
    <eLiterals name="LEFT" value="1" literal="left"/>
    <eLiterals name="RIGHT" literal="right"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SHOULD_REPEAT">
    <eLiterals name="DONT_REPEAT" literal="dontRepeat"/>
    <eLiterals name="DO_REPEAT" value="1" literal="doRepeat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RANDOM">
    <eLiterals name="NOT_RANDOM" literal="notRandom"/>
    <eLiterals name="RANDOM" value="1" literal="random"/>
  </eClassifiers>
</ecore:EPackage>
