/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.ui.tests;

import com.google.inject.Injector;
import dk.itu.dsl.roboprose.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RoboProseUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("dk.itu.dsl.roboprose.RoboProse");
	}

}
