/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.parser.antlr;

import com.google.inject.Inject;
import dk.itu.dsl.roboprose.parser.antlr.internal.InternalRoboProseParser;
import dk.itu.dsl.roboprose.services.RoboProseGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RoboProseParser extends AbstractAntlrParser {

	@Inject
	private RoboProseGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRoboProseParser createParser(XtextTokenStream stream) {
		return new InternalRoboProseParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RoboProse";
	}

	public RoboProseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RoboProseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
