/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.scoping;

import dk.itu.dsl.roboprose.scoping.AbstractRoboProseScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RoboProseScopeProvider extends AbstractRoboProseScopeProvider {
}
