/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.ui.contentassist;

import dk.itu.dsl.roboprose.ui.contentassist.AbstractRoboProseProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RoboProseProposalProvider extends AbstractRoboProseProposalProvider {
}
