// (c) mddbook, wasowski, tberger
//import sbt._
//import Dependencies._

lazy val mdsebook = RootProject(uri("https://bitbucket.org/modelsteam/mdsebook.git"))

lazy val mdsebookLocalBase = SettingKey[File]("mdsebookLocalBase",
    "local base direcotry for mdsebook")
mdsebookLocalBase := loadedBuild.value.units(mdsebook.build).localBase

lazy val root = (project in file("."))
.settings (
  inThisBuild(List(
    organization := "dk.itu.dsl.roboprose",
    scalaVersion := "2.12.3",
    version      := "0.1.0-SNAPSHOT"
  )),
  name := "dk.itu.dsl.roboprose.xtext.scala",
  // version := "0.03",
  // stick to Scala version supported by Scala IDE
  retrieveManaged := true,
  //EclipseKeys.relativizeLibs := true,

  scalacOptions += "-deprecation",
  scalacOptions += "-feature",
  scalacOptions += "-language:implicitConversions",

  // include the EMFScala "framework" (there is probably a better way to do it, to avoid rebuilding)
  unmanagedSourceDirectories in Compile += file(mdsebookLocalBase.value.absolutePath) /
    "mdsebook.scala/src/main/scala",
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) /
    "robo-prose-model/src/",
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) /
    "robo-prose-constraints/src/main/",


  // include the Code generated by Xtext
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) /
   "robo-prose-frontend/dk.itu.dsl.roboprose.richban.xtext/xtend-gen/",
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) /
   "robo-prose-frontend/dk.itu.dsl.roboprose.richban.xtext/src-gen/",
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) /
   "robo-prose-frontend/dk.itu.dsl.roboprose.richban.xtext/src/",

  unmanagedClasspath in Runtime += file(baseDirectory.value.getParent) /
   "robo-prose-frontend/dk.itu.dsl.roboprose.richban.xtext/src-gen/",

  libraryDependencies += "org.eclipse.xtext" % "org.eclipse.xtext" % "2.12.0",
  libraryDependencies += "org.scalatest" % "scalatest_2.12" % "3.0.4" % "test",
  // libraryDependencies += "org.bitbucket.inkytonik.kiama" %% "kiama" % "2.0.0"
).
dependsOn(mdsebook)
