/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RoboProseRuntimeModule extends AbstractRoboProseRuntimeModule {
}
