/**
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.ui;

import dk.itu.dsl.roboprose.ui.AbstractRoboProseUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RoboProseUiModule extends AbstractRoboProseUiModule {
  public RoboProseUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
