// (c) mddbook, wasowski, tberger

lazy val root = (project in file(".")).settings (

  organization := "roboprose",
  name := "dk.itu.dsl.roboprose.xtext.scala",
  version := "0.03",
  // stick to Scala version supported by Scala IDE 
  scalaVersion := "2.11.11",
  retrieveManaged := true,
  //EclipseKeys.relativizeLibs := true,

  scalacOptions += "-deprecation",
  scalacOptions += "-feature",
  scalacOptions += "-language:implicitConversions",

  // include the EMFScala "framework" (there is probably a better way to do it, to avoid rebuilding)
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) / "../mdsebook/mdsebook.scala/src/main/scala",
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) / "robo-prose-model/src/",

  // include the Code generated by Xtext
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) / "dk.itu.dsl.roboprose.xtext/xtend-gen/",
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) / "dk.itu.dsl.roboprose.xtext/src-gen/",
  unmanagedSourceDirectories in Compile += file(baseDirectory.value.getParent) / "dk.itu.dsl.roboprose.xtext/src/",

  unmanagedClasspath in Runtime += file(baseDirectory.value.getParent) / "dk.itu.dsl.roboprose.xtext/src-gen/",

  libraryDependencies += "org.eclipse.xtext" % "org.eclipse.xtext" % "2.12.0",
  libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.6" % "test"
  // libraryDependencies += "org.bitbucket.inkytonik.kiama" %% "kiama" % "2.0.0"
)
