/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.richban.xtext.ide


/**
 * Use this class to register ide components.
 */
class RoboProseIdeModule extends AbstractRoboProseIdeModule {
}
