/*
 * generated by Xtext 2.12.0
 */
package dk.itu.dsl.roboprose.ui;

import com.google.inject.Injector;
import dk.itu.dsl.roboprose.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RoboProseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtextActivator.getInstance().getInjector(XtextActivator.DK_ITU_DSL_ROBOPROSE_ROBOPROSE);
	}
	
}
